config/routes.rb
MeshiMatching::Application.routes.draw do
  match '/result', to: 'users#result', via: 'get'
  match '/home', to: 'users#home', via: 'get'
  match '/new', to: 'users#new', via: 'get'
  match '/edit', to: 'users#edit', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'users#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save do
    self.name = name.downcase
    self.mail = mail.downcase
  end

  before_create :create_remember_token

  validates :name, length: { maximum: 30 }, uniqueness: true

  # チェック用変数
  description = {
    name: "ユーザー名",
    mail: "メールアドレス",
    password: "パスワード",
    password_confirmation: "確認用パスワード"
  }

  name_min_length = 6
  name_max_length = 30
  password_min_length = 6
  password_max_length = 30

  # 必須チェック
  required_columns = [:name, :mail, :password, :password_confirmation]
  required_columns.each do |column|
    validates_presence_of column, message: "#{description[column]}を入力してください。"
  end

  # ユニークチェック
  unique_columns = [:name, :mail]
  unique_columns.each do |column|
    validates_uniqueness_of column, message: "#{description[column]}はすでに使われています。", case_sensitive: false
  end

  # 長さチェック
  length_columns = {
    name: {min: name_min_length, max: name_max_length},
    password: {min: password_min_length, max: password_max_length},
  }

  length_columns.each do |column, length|
    validates_length_of column, minimum: length[:min], message: "#{description[column]}は最低#{length[:min]}文字以上必要です。"
    validates_length_of column, maximum: length[:max], message: "#{description[column]}は最大#{length[:max]}文字です。"
  end

  # メアドの体裁チェック
  VALID_MAIL_ADDRESS = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :mail, with: VALID_MAIL_ADDRESS, message: "不正なメールアドレスです。"


  # 安全なパスワードを使う
  has_secure_password


  # remember_tokenを作る
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # tokenを暗号化
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # remember_tokenを作成
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # 入力されたユーザー名からUserモデルを検索
    user = User.find_by_name(params[:session][:name].downcase)

    if user and user.authenticate(params[:session][:password])
      # ユーザーをサインインして、検索ページに飛ぶ
      sign_in user
      redirect_to user
    else
      # エラーメッセージ出して、ページ遷移なし
      flash.now[:danger] = "ユーザー名またはパスワードが正しくありません"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  # 検索結果表示
  def result
  end

  # ホーム
  def home
  end

  # 各ユーザーのデータを表示
  def show
    @user = User.find_by_id(params[:id])
  end

  # ユーザーの新規作成
  def new
    @user = User.new
  end

  # ユーザー情報の編集
  def edit
    # @user = User.find_by_id(params[:id])
    @user = current_user
  end

  # edit時の情報を保存
  def update
    @user = current_user

    if @user.update_attributes(user_params)
      # 更新成功時
      flash.now[:success] = "ユーザー情報を変更しました"
      redirect_to @user
    else
      # 更新失敗時
      render 'edit'
    end
  end

  # 登録ボタン時のアクション
  def create
    @user = User.new(user_params)

    if @user.save
      # 保存成功時
      sign_in @user
      flash.now[:success] = "登録ありがとうございます。"
      redirect_to @user
    else
      # 保存失敗時
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :mail, :password, :password_confirmation)
  end

  # ログインしてないとeditとupdateをさせない
  def signed_in_user
    unless signed_in?
      flash[:danger] = "ログインしてください"
      redirect_to signin_url
    end
  end

  # ログインユーザーが正しいか判定
  def correct_user
    @user = User.find_by_id(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ユーザーがログインしてるかを返す
  def login? user
    return user.login if user
    false
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # サインインする
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  # サインアウトする
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  # session内のユーザーを取得
  def current_user=(user)
    @current_user = user
  end

  # ログイン中のユーザーか判定
  def current_user?(user)
    user == current_user
  end

  # sessionにユーザーをセット
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by_remember_token remember_token
  end

  # サインイン判定
  def signed_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>飯マッチング | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <% if signed_in? %>
      <p><%= "#{current_user.name}さん" %></p>
      <%= link_to "設定", edit_user_path(current_user), method: "get" %>
      <%= link_to "サインアウト", signout_path, method: "delete" %>
    <% else %>
      <%= link_to "ログイン", signin_path %>
      <%= link_to "ユーザー登録", new_path %>
    <% end %>
  </header>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>

  <%= yield %>

  <%= debug(params) if Rails.env.development? %>

  <footer>
    <a data-toggle="modal" id="help-link" href="#help-modal">ヘルプ</a>

    <div id="help-modal" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3>飯マッチングについて</h3>
          </div>
          <div class="modal-body">
            <p>
              飯マッチングは食べ物のジャンルと店の場所から、レストランを一軒だけ検索するアプリです。どこでご飯を食べようか考えるのが面倒なときにお使いください。
            </p>
          </div>
          <div class="modal-footer">
            <p>
              made by kentana
            </p>
            <p>
              powered by ぐるなび
            </p>
          </div>
        </div>
      </div>
    </div>

    <%# <%= image_tag ぐるなびの画像%>
  </footer>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "MeshiMatching"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#"MeshiMatching
          .container.nav-collapse
            ul.nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"
    
      footer
        p &copy; Company 2014

app/views/shared/_error_messages.html.slim
- errors = @user.errors.select {|e| e[1].match(/。/)}
- if errors.any?
  .alert.alert-danger
    p = "入力データに#{errors.count}個のエラーがあります。"

    ul#error-list
      - for msg in errors
        li = msg[1]

app/views/users/edit.html.slim
- provide(:title, "編集")
- signup_elements = { name: "ユーザー名",
                      password: "パスワード",
                      password_confirmation: "パスワードを再入力",
                      mail: "メールアドレス",
                      # default_category: "デフォルトで検索するジャンル",
                      # default_area: "デフォルトで検索する地域",
                    }

= stylesheet_link_tag "signup"

#edit
  #edit-window
    = form_for(@user) do |f|
      = render 'shared/error_messages'
      - for element in signup_elements
        = f.text_field element[0], class: "user-info", placeholder: "#{element[1]}"

      input#signup-button.btn-primary.btn[type="submit" value="ユーザー情報変更"]

app/views/users/home.html.slim
- provide(:title, "Home")

- search_elements = { category: "ジャンル（例: 寿司）",
                      area: "地域（例: 渋谷）",
                    }

= stylesheet_link_tag "home"

#home
  #logo-area
    = image_tag "/logos/search_logo.png", :id => "search-logo"

  #search-area
    - for element in search_elements
      input.search-box[id="#{element[0]}" placeholder="#{element[1]}"]

    input#search-button.btn.btn-danger[type="button" value="マッチング"]

app/views/users/new.html.slim
- provide(:title, "登録")
- signup_elements = { name: "ユーザー名",
                      password: "パスワード",
                      password_confirmation: "パスワードを再入力",
                      mail: "メールアドレス",
                      # default_category: "デフォルトで検索するジャンル",
                      # default_area: "デフォルトで検索する地域",
                    }

= stylesheet_link_tag "signup"

#signup
  #signup-window
    = form_for(@user) do |f|
      = render 'shared/error_messages'
      - for element in signup_elements
        = f.text_field element[0], class: "user-info", placeholder: "#{element[1]}"

      input#signup-button.btn-primary.btn[type="submit" value="登録"]

app/views/users/result.html.slim
- provide(:title, "結果")

= stylesheet_link_tag "result"

#result
  = image_tag "/logos/result_logo.png"

  #result-area
    h3#restaurant-name 店名
    img#restaurant-image
    p#restaurant-description 店についての説明

    p#access アクセス
    p#address 住所

    #map-area
      img#map
      p#access-description どこ駅から徒歩何分的な

app/views/users/show.html.slim
- display_items = { name: "ユーザー名",
                    mail: "メールアドレス",
                    password: "パスワード",
                    default_category: "デフォルトで検索するジャンル",
                    default_area: "デフォルトで検索するエリア",
                  }

#user-page
  #user-info
    - for item in display_items
      p.item-name = item[1]
      p.item-content = @user[item[0]]

  #button-area
    = link_to "マッチング", home_path, class: "btn btn-danger"